import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { AuthProvider } from "@/components/providers/AuthProvider";
import { ProductCacheProvider } from "@/contexts/ProductCacheContext";
import { RequestCacheProvider } from "@/contexts/RequestCacheContext";
import { MarketplaceCacheProvider } from "@/contexts/MarketplaceCacheContext";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <ProductCacheProvider>
            <MarketplaceCacheProvider>
              <RequestCacheProvider>
                {children}
              </RequestCacheProvider>
            </MarketplaceCacheProvider>
          </ProductCacheProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
